package top.kmar.php.ir;

/** 非短路二元运算；逻辑异或同样需要两个操作数，区别于短路 AND 和 OR。 */
public enum BinaryOperator {
    ADD, SUBTRACT, MULTIPLY, DIVIDE, MODULO, POWER, CONCAT,
    SHIFT_LEFT, SHIFT_RIGHT, BITWISE_AND, BITWISE_OR, BITWISE_XOR,
    EQUAL, NOT_EQUAL, IDENTICAL, NOT_IDENTICAL, SPACESHIP,
    LESS, LESS_EQUAL, GREATER, GREATER_EQUAL, LOGICAL_XOR
}
